window.NOVA_EDIT=(function Editors(A){
const N=window.NOVA,V=window.NOVA_VIEWS,S=N.get,E=N.escape;
const f=(label,name,type="text",value="",extra="")=>`<div class="field"><label>${E(label)}</label><input name="${name}" type="${type}" value="${E(value)}" ${extra}></div>`;
const sel=(label,name,arr,value)=>`<div class="field"><label>${E(label)}</label><select name="${name}">${V.option(arr,value)}</select></div>`;
let submit=null;
function close(){N.$("modal").close();submit=null}
function open(title,fields,cb,remove){submit=cb;N.$("modalBody").innerHTML=`<div class="modal-header"><h2>${E(title)}</h2><button type="button" data-action="close" class="modal-close">×</button></div><div class="modal-content"><form id="editorForm">${fields}<div class="modal-actions">${remove?'<button type="button" id="removeItem" class="danger-btn">Delete</button>':""}<button type="button" data-action="close" class="secondary-btn">Cancel</button><button type="submit" class="primary-btn">Save</button></div></form></div>`;N.$("modal").showModal();if(remove)N.$("removeItem").onclick=remove;}
function save(form){if(submit&&submit(new FormData(form))!==false)close()}
function subject(id){const old=S().subjects.find(x=>x.id===id),fields=f("Subject / course name","name","text",old?.name||"",'maxlength="120" required')+sel("Color","color",N.colors.map((x,i)=>[x,"Color "+(i+1)]),old?.color||N.colors[S().subjects.length%N.colors.length]);open(old?"Edit subject":"Add subject",fields,data=>{const name=String(data.get("name")||"").trim().slice(0,120);if(!name)return A.toast("Enter a subject."),false;if(S().subjects.some(x=>x.id!==id&&x.name.toLowerCase()===name.toLowerCase()))return A.toast("Duplicate subject."),false;const color=N.colors.includes(data.get("color"))?data.get("color"):N.colors[0];if(old)Object.assign(old,{name,color});else S().subjects.push({id:N.uid(),name,color});A.changed();return true;},old?()=>{if(!confirm("Delete subject? Current routine entries will remain unassigned."))return;S().subjects=S().subjects.filter(x=>x.id!==id);A.changed();close()}:null)}
function session(id){const old=S().sessions.find(x=>x.id===id),v=old||{subjectId:S().subjects[0]?.id||"",day:A.day(),type:"Class",start:"09:00",end:"10:00",title:"",place:""};const fields=sel("Subject","subjectId",[["","Personal / None"],...S().subjects.map(x=>[x.id,x.name])],v.subjectId)+f("Custom activity title","title","text",v.title||"",'maxlength="100"')+'<div class="form-grid">'+sel("Day","day",N.DAYS.map((x,i)=>[i,x]),v.day)+sel("Type","type",["Class","Study","Lab","Revision","Exam","Break","Sleep","Meal","Exercise","Prayer","Commute","Personal","Other"],v.type)+f("Start","start","time",v.start,"required")+f("End","end","time",v.end,"required")+"</div>"+f("Room / note","place","text",v.place||"",'maxlength="100"');
open(old?"Edit session":"Add session",fields,data=>{const day=Number(data.get("day")),start=String(data.get("start")),end=String(data.get("end"));if(!Number.isInteger(day)||day<0||day>6||!start||!end||N.min(end)<=N.min(start))return A.toast("End must be after start."),false;
const overlap=S().sessions.some(x=>x.id!==id&&x.day===day&&N.min(start)<N.min(x.end)&&N.min(end)>N.min(x.start));if(overlap&&!confirm("Overlaps another session. Save anyway?"))return false;
const rec={id:old?.id||N.uid(),day,start,end,subjectId:String(data.get("subjectId")||""),type:String(data.get("type")||"Class"),title:String(data.get("title")||"").trim().slice(0,100),place:String(data.get("place")||"").trim().slice(0,100)};if(old)Object.assign(old,rec);else S().sessions.push(rec);A.setDay(day);A.changed();return true;},old?()=>{if(!confirm("Delete this session?"))return;S().sessions=S().sessions.filter(x=>x.id!==id);A.changed();close()}:null)}
function task(id){const old=S().tasks.find(x=>x.id===id),v=old||{title:"",subjectId:"",due:N.date(new Date()),priority:"medium"};const fields=f("Task / goal","title","text",v.title,'maxlength="250" required')+sel("Subject","subjectId",[["","Personal / General"],...S().subjects.map(x=>[x.id,x.name])],v.subjectId)+'<div class="form-grid">'+f("Due date","due","date",v.due||"")+sel("Priority","priority",["low","medium","high"],v.priority)+"</div>";
open(old?"Edit task":"New task",fields,data=>{const title=String(data.get("title")||"").trim().slice(0,250);if(!title)return A.toast("Enter a task title."),false;const rec={id:old?.id||N.uid(),title,subjectId:String(data.get("subjectId")||""),due:String(data.get("due")||""),priority:String(data.get("priority")||"medium"),done:old?.done||false};if(old)Object.assign(old,rec);else S().tasks.push(rec);A.changed();return true;},old?()=>{if(!confirm("Delete task?"))return;S().tasks=S().tasks.filter(x=>x.id!==id);A.changed();close()}:null)}
function planner(){const fields='<div class="hint-banner">Generates study blocks without deleting existing events.</div><div class="form-grid">'+sel("Days","days",[1,2,3,4,5,6,7],5)+sel("Blocks / day","blocks",[1,2,3,4,5,6],2)+f("Start time","start","time","16:00","required")+sel("Minutes / block","length",[25,30,40,45,50,60,75,90],50)+sel("Break minutes","breakTime",[0,5,10,15,20,30],10)+"</div>";open("Auto study planner",fields,data=>{const r=N.addStudy({days:Number(data.get("days")),blocks:Number(data.get("blocks")),start:String(data.get("start")),length:Number(data.get("length")),breakTime:Number(data.get("breakTime"))});A.changed();A.toast(r.added+" blocks created; "+r.skipped+" skipped.");return true;})}
function install(){if(A.installPrompt()){A.installPrompt().prompt();A.installPrompt().userChoice.then(()=>A.clearInstallPrompt());return}open("Install NovaStudy",'<div class="hint-banner"><b>Android:</b> Chrome ⋮ → Install app.<br><br><b>iOS:</b> Safari Share → Add to Home Screen.<br><br><b>Desktop:</b> Chrome/Edge install icon.<br><br>Requires HTTPS or localhost.</div>',()=>true)}
return{subject,session,task,planner,install,close,save}
});