(function pages(){
const N=window.NOVA,{C,DAYS,escape:E,get,name,color,hour,date}=N;
const s=()=>get(),button=(t,a,cls="primary-btn",id="")=>`<button class="${cls}" data-action="${a}" ${id?`data-id="${E(id)}"`:""}>${t}</button>`;
const heading=(eyebrow,title,subtitle,actions="")=>`<div class="page-head"><div><span class="eyebrow">${eyebrow}</span><h1 class="view-title">${title}</h1><p class="subheading">${subtitle}</p></div><div class="head-actions">${actions}</div></div>`;
const empty=text=>`<div class="empty-state">✦ ${text}</div>`;
const option=(values,selected)=>values.map(x=>{const [value,label]=Array.isArray(x)?x:[x,x];return `<option value="${E(value)}" ${String(value)===String(selected)?"selected":""}>${E(label)}</option>`}).join("");
const session=(x,edit=false)=>`<div class="timeline-card"><div class="time-label">${E(hour(x.start))}<small>${E(hour(x.end))}</small></div><div class="time-line" style="background:${E(color(x.subjectId))}"></div><div class="session-text"><b>${E(x.title||name(x.subjectId))}</b><small>${E(x.type||"Class")}${x.place?" • "+E(x.place):""}</small></div>${edit?`<div class="card-actions">${button("Edit","edit-session","tiny-btn",x.id)}${button("×","delete-session","tiny-btn",x.id)}</div>`:`<span class="chip">${E(x.type||"Class")}</span>`}</div>`;
const task=(t,edit=false)=>`<div class="task-row"><input class="task-tick" type="checkbox" data-task-check="${E(t.id)}" ${t.done?"checked":""} aria-label="Mark task complete"><div class="task-main"><b class="${t.done?"task-done":""}">${E(t.title)}</b><small>${E(t.subjectId?name(t.subjectId):"General")}${t.due?" • "+E(t.due):""}</small></div><span class="priority ${E(t.priority||"medium")}">${E(t.priority||"medium")}</span>${edit?`<div class="card-actions">${button("Edit","edit-task","tiny-btn",t.id)}${button("×","delete-task","tiny-btn",t.id)}</div>`:""}</div>`;
function dashboard(){const now=new Date(),events=s().sessions.filter(x=>x.day===now.getDay()).sort((a,b)=>a.start.localeCompare(b.start)),pending=s().tasks.filter(x=>!x.done),done=s().tasks.length-pending.length,hours=events.reduce((n,x)=>n+Math.max(0,N.min(x.end)-N.min(x.start))/60,0),pct=s().tasks.length?Math.round(done/s().tasks.length*100):0;
return heading("MISSION CONTROL / 01","Your student dashboard","Daily schedule, missions and progress in one futuristic workspace.",button("+ New session","add-session"))+
`<div class="hero"><div class="hero-copy"><span class="eyebrow">STUDY INTELLIGENCE · ONLINE</span><h2>Welcome back, ${E(s().profile.name.split(" ")[0]||"Student")} ✦</h2><p>Plan smarter. Focus deeper. Make every session count, from school to university.</p><div class="hero-actions">${button("Build my routine →","add-session")}${button("Auto study plan","auto-plan","secondary-btn")}</div></div><div class="orbit"><div class="orbit-core">N<small>✦</small></div></div></div>
<div class="grid-4">${[["◷",events.length,"Sessions today"],["◎",Math.round(hours*10)/10+"h","Planned hours"],["☑",pending.length,"Pending missions"],["⌁",pct+"%","Task completion"]].map(x=>`<div class="panel stat"><div class="stat-icon">${x[0]}</div><div class="stat-value">${x[1]}</div><small>${x[2]}</small></div>`).join("")}</div>
<div class="grid-2"><section class="panel"><div class="panel-header"><div><b class="panel-title">Today's timeline</b><small class="panel-sub">${E(DAYS[now.getDay()])} • ${date(now)}</small></div>${button("See all →","go-schedule","tiny-btn")}</div>${events.length?events.map(x=>session(x)).join(""):empty("No sessions yet. Add a class, lab or study session.")}</section>
<section class="panel"><div class="panel-header"><div><b class="panel-title">Upcoming missions</b><small class="panel-sub">Your next goals</small></div>${button("View all →","go-tasks","tiny-btn")}</div>${pending.length?pending.slice(0,6).map(x=>task(x)).join(""):empty("No pending tasks. Enjoy the progress!")}</section></div>`}
function schedule(day){const days=Array.from({length:7},(_,i)=>(Number(s().profile.weekStart)||0)+i).map(x=>x%7),events=s().sessions.filter(x=>x.day===day).sort((a,b)=>a.start.localeCompare(b.start));
return heading("TIME MATRIX / 02","Your 7-day timetable","Weekly classes, revision, activities and study blocks.",button("+ Add session","add-session")+button("⚡ Generate study time","auto-plan","secondary-btn"))+
`<div class="day-pills">${days.map(d=>`<button class="day-pill ${d===day?"active":""}" data-action="day" data-day="${d}">${DAYS[d].slice(0,3)}<small>${s().sessions.filter(x=>x.day===d).length} blocks</small></button>`).join("")}</div>
<section class="panel"><div class="panel-header"><div><b class="panel-title">${DAYS[day]} routine</b><small class="panel-sub">${events.length} sessions • editable</small></div><span class="chip">24-hour scheduling</span></div>${events.length?events.map(x=>session(x,true)).join(""):empty("Nothing planned here yet.")}</section><div class="hint-banner">Overlaps are warned about when saving. Auto study planner avoids occupied time slots.</div>`}
function tasks(filter,search){const list=s().tasks.filter(t=>(filter==="all"||filter==="pending"&&!t.done||filter==="done"&&t.done)&&(t.title+" "+name(t.subjectId)).toLowerCase().includes(search.toLowerCase())).sort((a,b)=>Number(a.done)-Number(b.done)||(a.due||"9999").localeCompare(b.due||"9999"));
return heading("MISSION TRACKER / 03","Tasks & goals","Assignments, exam prep and personal to-dos.",button("+ New task","add-task"))+`<div class="toolbar"><div class="filter-row">${["all","pending","done"].map(x=>`<button class="filter-chip ${filter===x?"active":""}" data-action="filter" data-filter="${x}">${x.toUpperCase()}</button>`).join("")}</div><input type="search" placeholder="Search tasks…" id="taskSearch" aria-label="Search tasks" value="${E(search)}"></div><section class="panel">${list.length?list.map(x=>task(x,true)).join(""):empty("No missions match this filter.")}</section>`}
function subjects(){const suggestions=N.subjectPreset().filter(x=>!s().subjects.some(z=>z.name.toLowerCase()===x.toLowerCase()));return heading("KNOWLEDGE LIBRARY / 04","Subject library","Choose subjects for your own academic level and curriculum.",button("+ Add subject","add-subject")+button("Import suggestions ("+suggestions.length+")","suggestions","secondary-btn"))+
`<div class="flex-between"><b class="section-caption">MY SUBJECTS / ${s().subjects.length}</b><span class="chip">${E(C[s().profile.category].name)} • ${E(s().profile.track)}</span></div><div class="subject-grid">${s().subjects.length?s().subjects.map(x=>`<div class="subject-card" style="--subject-color:${E(N.colors.includes(x.color)?x.color:N.colors[0])}"><div class="subject-card-head"><div class="subject-initial">${E(x.name.slice(0,1))}</div>${button("Edit","edit-subject","tiny-btn",x.id)}</div><b>${E(x.name)}</b><small>${s().sessions.filter(t=>t.subjectId===x.id).length} weekly sessions</small></div>`).join(""):empty("Add your first course or import suggestions.")}</div><div class="hint-banner">Suggestions are customizable examples, not the official syllabus of any education board or university.</div>`}
function settings(){const p=s().profile,c=C[p.category];return heading("IDENTITY SYSTEM / 05","Profile & settings","Your class, category, group, preferences and local backups.",button("⇩ Install app","install","secondary-btn"))+
`<div class="settings-grid"><section class="panel"><div class="panel-header"><b class="panel-title">Academic profile</b><span class="chip">STUDENT ID</span></div><form id="profileForm" class="form-grid">
<div class="field"><label>Your name</label><input name="name" required maxlength="80" value="${E(p.name)}"></div><div class="field"><label>Institution (optional)</label><input name="institution" maxlength="100" value="${E(p.institution||"")}"></div>
<div class="field"><label>Education category</label><select id="profileCategory" name="category">${option(Object.entries(C).map(([k,v])=>[k,v.name]),p.category)}</select></div>
<div class="field"><label>Class / academic year</label><select id="profileLevel" name="level">${option(c.levels,p.level)}</select></div>
<div class="field wide"><label>Group / department</label><select id="profileTrack" name="track">${option(Object.keys(c.tracks),p.track)}</select></div>
<div class="field wide"><label>Week begins</label><select name="weekStart">${option([[6,"Saturday"],[0,"Sunday"],[1,"Monday"]],p.weekStart)}</select></div><div class="wide"><button class="primary-btn" type="submit">Save profile →</button></div></form>
<div class="hint-banner">Changing class or subject group never deletes existing routines, subjects or missions.</div></section>
<section class="panel"><div class="panel-header"><b class="panel-title">Data & notifications</b><span class="chip">LOCAL FIRST</span></div><div class="appearance-panel appearance-panel-v12">
  <div class="appearance-copy">
    <b>Choose your theme</b>
    <small>Choose an interface style without changing your saved routine, tasks, or subjects.</small>
  </div>
  <div class="theme-gallery" role="group" aria-label="Appearance theme">
    <button type="button" class="theme-option" data-action="theme-select" data-theme-value="cyber" aria-pressed="false" aria-label="Use Futuristic Cyber theme">
      <span class="theme-preview theme-preview-cyber" aria-hidden="true"><span class="preview-top"></span><span class="preview-main"><i></i><b></b><em></em></span></span>
      <span class="theme-option-bottom"><span class="theme-option-name"><strong>Futuristic Cyber</strong><small>Cyan + violet</small></span><span class="theme-check" aria-hidden="true">✓</span></span>
    </button>
    <button type="button" class="theme-option" data-action="theme-select" data-theme-value="gold" aria-pressed="false" aria-label="Use Black and Gold theme">
      <span class="theme-preview theme-preview-gold" aria-hidden="true"><span class="preview-top"></span><span class="preview-main"><i></i><b></b><em></em></span></span>
      <span class="theme-option-bottom"><span class="theme-option-name"><strong>Black & Gold</strong><small>Midnight + gold</small></span><span class="theme-check" aria-hidden="true">✓</span></span>
    </button>
  </div>
  <small class="theme-save-note">Your appearance preference is saved on this device, including after refresh.</small>
</div><hr class="separator"><p class="panel-sub">Your routines are saved in THIS browser, not in a cloud database. Export regularly to avoid losing data.</p><div class="settings-actions">${button("⇩ Export JSON backup","export","secondary-btn")}<label class="import-label">⇧ Import backup<input type="file" id="importFile" accept=".json,application/json"></label></div><hr class="separator">
<label class="toggle-line"><span><b>In-app reminders</b><small>Only while app is open; no background alarms</small></span><input type="checkbox" id="remindersSwitch" ${p.reminders?"checked":""}></label>
<div class="hint-banner">PWA works over HTTPS/localhost after first load. Installing does not create an Android APK or iOS IPA.</div></section></div>`}
window.NOVA_VIEWS={button,heading,empty,option,session,task,dashboard,schedule,tasks,subjects,settings};
})();